{{- if .Values.ingress.enabled -}}
{{- $fullName := include "host.fullname" . -}}
{{- $servicePort := .Values.service.port -}}
{{- $ingressPath := .Values.ingress.path -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ template "host.name" . }}
    chart: {{ template "host.chart" . }}
    release: {{ .Release.Name }}
spec:
  entryPoints:
  {{- range .Values.ingress.entryPoints }}
    - {{ . }}
  {{- end }}
  routes:
  {{- range .Values.ingress.hosts }}
  - match: Host(`{{ . }}`) && PathPrefix(`{{ $ingressPath }}`)
    kind: Rule
    services:
    - name: {{ $fullName }}
      port: {{ $servicePort }}
    middlewares:
        - name: {{ $fullName }}
  {{- end }}
  tls:
    certResolver: default
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ template "host.name" . }}
    chart: {{ template "host.chart" . }}
    release: {{ .Release.Name }}
spec:
  stripPrefix:
    prefixes:
      - {{ $ingressPath }}
{{- end }}