version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/src/ClientApp"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
