# ASP.NET Core
# Build and test ASP.NET Core web applications targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/dotnet-core

name: 0.15.0$(Rev:.r)

pool:
  vmImage: 'ubuntu-latest'
  
variables:
  buildConfiguration: 'Release'
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

steps:
- task: UseDotNet@2
  displayName: Use dotnet core SDK
  inputs:
    packageType: 'sdk'
    version: '3.1.x'

- script: dotnet tool restore
  displayName: Restore tools

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
  
- script: dotnet publish src/Host --configuration $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)/build/host
  displayName: Publish host
  
#- script: dotnet publish src/Channels.Host --configuration $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)/channels
#  displayName: Publish channels
#- script: dotnet publish src/Messages.Host --configuration $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)/messages
#  displayName: Publish messages
- task: PublishBuildArtifacts@1
  displayName: Publish build
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)/build' 
    artifactName: 'build' 
    #publishLocation: 'Container' # Options: container, filePath
    #targetPath: # Required when publishLocation == FilePath
    #parallel: false # Optional
    #parallelCount: # Optional

- task: PublishBuildArtifacts@1
  displayName: Publish helm charts
  inputs:
    pathtoPublish: 'charts' 
    artifactName: 'charts' 

- task: DockerInstaller@0
  displayName: Docker Installer
  inputs:
    dockerVersion: 18.06.3-ce
    releaseType: stable

- task: Docker@2
  displayName: Login to Docker Hub
  inputs:
    command: login
    containerRegistry: DockerHub

- task: Docker@2
  displayName: Build and Push - channels
  inputs:
    command: buildAndPush
    repository: tankagql/samples-chat-channels
    buildContext: .
    Dockerfile: src/Channels.Host/Dockerfile
    tags: |
      $(Build.BuildNumber)
      latest

- task: Docker@2
  displayName: Build and Push - messages
  inputs:
    command: buildAndPush
    repository: tankagql/samples-chat-messages
    buildContext: .
    Dockerfile: src/Messages.Host/Dockerfile
    tags: |
      $(Build.BuildNumber)
      latest

- task: Docker@2
  displayName: Build and Push - gw
  inputs:
    command: buildAndPush
    repository: tankagql/samples-chat-gw
    buildContext: .
    Dockerfile: src/Host/Dockerfile
    tags: |
      $(Build.BuildNumber)
      latest

- task: Docker@2
  displayName: Build and Push - frontend
  inputs:
    command: buildAndPush
    repository: tankagql/samples-chat
    buildContext: src/ClientApp
    Dockerfile: src/ClientApp/Dockerfile
    tags: |
      $(Build.BuildNumber)
      latest
