# ASP.NET Core
# Build and test ASP.NET Core web applications targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/dotnet-core

name: 'graphql-samples'

pool:
  vmImage: 'windows-2019'

variables:
  buildConfiguration: 'Release'
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

steps:
- task: DotNetCoreInstaller@0
  displayName: Install SDK
  inputs:
    packageType: sdk
    version: '2.2.105'

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- script: dotnet publish --configuration $(buildConfiguration)
  displayName: 'dotnet publish $(buildConfiguration)'
