version: '3'
services:
  channels:
    build:
      context: .
      dockerfile: src/Channels.Host/Dockerfile
    #ports:
    #  - "5010:80"
    environment: 
      ASPNETCORE_ENVIRONMENT: "Production"
      JWT__Authority: "https://tanka.eu.auth0.com/"
      JWT__Audience: "https://tanka-chat.azurewebsites.net/api"
  
  messages:
    build:
      context: .
      dockerfile: src/Messages.Host/Dockerfile
    #ports:
    #  - "5011:80"
    environment: 
      ASPNETCORE_ENVIRONMENT: "Production"
      JWT__Authority: "https://tanka.eu.auth0.com/"
      JWT__Audience: "https://tanka-chat.azurewebsites.net/api"
  
  gateway:
    build:
      context: .
      dockerfile: src/Host/Dockerfile
    ports:
      - "5002:80"
    environment: 
      ASPNETCORE_ENVIRONMENT: "Production"
      JWT__Authority: "https://tanka.eu.auth0.com/"
      JWT__Audience: "https://tanka-chat.azurewebsites.net/api"
      Remotes__Channels: "http://channels/hubs/graphql"
      Remotes__ChannelsHttp: "http://channels/api/graphql"
      Remotes__Messages: "http://messages/hubs/graphql"
      
  frontend:
    build:
      context: src/ClientApp
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment: 
      NODE_ENV: "Production"
      REACT_APP_CLIENT_ID: "W4MlLkgw5lJCH2ejTrJ7uFBdNfQb6w-5"
      REACT_APP_DOMAIN: "tanka.eu.auth0.com"
      REACT_APP_REDIRECT_URI: "http://localhost:5001/callback"
      REACT_APP_RESPONSE_TYPE: "token id_token"
      REACT_APP_SCOPE: "openid email profile"
      REACT_APP_AUDIENCE: "https://tanka-chat.azurewebsites.net/api"
      REACT_APP_HOST: "http://localhost:5002"
      REACT_APP_BASE: "/"